// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/users/[id].ts";
import * as $3 from "./routes/users/[id].tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/users/[id].ts": $2,
    "./routes/users/[id].tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
